#ifndef __AUSEX_TEMPERATURE_SENSOR_H__
#define __AUSEX_TEMPERATURE_SENSOR_H__

#include "AusEx.h"

#define AUSEX_TEMPERATURE_CLASS AusExGroveTemperatureSensor
#define AUSEX_GROVE_TEMPERATURE_SENSOR_NAME "AusExGroveTemperatureSensor"
#define AUSEX_GROVE_TEMPERATURE_SENSOR_TYPE SENSOR_TYPE_SIMPLE
#define AUSEX_GROVE_TEMPERATURE_SENSOR_LIBRARY_VERSION 1
#define AUSEX_GROVE_TEMPERATURE_SENSOR_RETURN_VALUE temperature
#define AUSEX_GROVE_TEMPERATURE_SENSOR_VALUE_TYPE float
#define AUSEX_GROVE_TEMPERATURE_SENSOR_VDD 5
#define AUSEX_GROVE_TEMPERATURE_SENSOR_MIN_VALUE -40.0
#define AUSEX_GROVE_TEMPERATURE_SENSOR_MAX_VALUE 125
#define AUSEX_GROVE_TEMPERATURE_SENSOR_RESOLUTION 0.1611328125
#define AUSEX_GROVE_TEMPERATURE_SENSOR_MIN_DELAY 0
#define AUSEX_GROVE_TEMPERATURE_SENSOR_INIT_DELAY 0

#define AUSEX_GROVE_TEMPERATURE_SENSOR_THERMISTER_B_VALUE 4275
#define AUSEX_GROVE_TEMPERATURE_SENSOR_RESISTER_R0 100000

class AUSEX_TEMPERATURE_CLASS : public Adafruit_SensorEx {
public:
  AUSEX_TEMPERATURE_CLASS(int, float vdd=AUSEX_GROVE_TEMPERATURE_SENSOR_VDD, int32_t sensorID = -1);
  bool begin(void);
  bool getEvent(sensors_event_t*);
  void getSensor(sensor_t*);
  bool enableAutoRange(bool);
  int setMode(int);
  int getMode();

private:
  int _pin;
  float _vdd;
  int32_t _sensorID;
  AUSEX_GROVE_TEMPERATURE_SENSOR_VALUE_TYPE calcValue(int);
  bool _autoRange;
};



#endif /* __AUSEX_TEMPERATURE_SENSOR_H__ */
